server.port: 8084
spring.application.name: GATEWAY-SERVICE

# Eureka Client Configuration
eureka.instance.prefer-ip-address: true
eureka.client.fetch-registry: true
eureka.client.register-with-eureka: true
eureka.client.service-url.defaultZone: http://localhost:8761/eureka



# API-GATEWAY Configuration
spring:
  cloud:
    gateway:
      routes:
        # Service one
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customer/**
        # service two
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/hotel/**,/api/staff/**
        # Service three
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/rating/**





